name = "websitev2"
pages_build_output_dir = ".open-next"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

# Preview environment
[env.preview]
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]
