name = "websitev2"
main = ".open-next/worker.js"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Preview environment
[env.preview]
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]
